# Лабораторная работа №5

## Задание:

1 Считать в pandas DataFrame любой источник данных: CSV, JSON, Excel-файл, HTML-таблицу, встроенный датасет sklearn. Опишите ваши данные, что обозначает каждый столбец, какого типа (категориальный, вещественный, целочисленный, бинарный) данный столбец, при необходимости для категориальных в том числе бинарных признаков привести расшифровку их значений. В общем, проведите "визуальный" анализ ваших данных.

2 Выполните с датафреймом следующие операции (многие операции можно совершить не одним способом, используйте все известные вам способы, поищите/придумайте новые способы) :

2.1 вывод таблицы

2.2 вывод первых 5 элементов таблицы

2.3 вывод последних 5 элементов таблицы

2.4 использовать функцию describe()

2.5 считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки) всеми известными вам способами

2.6 фильтрация строк по диапазону индекса

2.7 фильтрация набора данных по какому-либо условию

2.8 работа с пропущенными значениями (если они есть): удаление строк с пропущенными значениями, заполнение пропущенных значений средним значением по колонке. Если пропущенных значений нет — намеренно их "генерируете", прибивая какие-то куски данных в np.nan

2.9. создание нового поля вычисленного на основе значений других полей:

2.9.1 через выражение на базе имеющихся колонок,

2.9.2 через DataFrame.apply

2.9.3 через Series.apply

2.10 сортировка по какому-либо из полей

2.11 вычислить несколько статистик по колонкам (используйте встроенные агрегатные функции — любые на выбор)

2.12 .value_counts()

2.13 Вывод уникальных значений колонки через .unique()

2.14 Удалите текущий индекс и создайте новый индекс на базе новой колонки, которая для этого лучше всего подходит

## Код программы:

### 1. Импортируем библиотеки и загружаем данные из CSV файла:

* name - название (строковый)
* year - год (дата)
* selling_price - цена продажи (целочисленный)
* km_driven - пробег (целочисленный)
* fuel - тип топливо (стрковой)
* seller_type - продавец (строковой)
* transmission - трансимиссия (строковой)
* owner - какой по счету владелец (строковой)

In [26]:
import pandas as pd
import numpy as np
pd.options.display.float_format = None
df = pd.read_csv("cars.csv")
df.replace(0, np.nan, inplace=True)

### 2.1 вывод таблицы

In [27]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

вывод в формате Jupyter Notebook:

In [28]:
display(df)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

вывод в виде строки:

In [29]:
print(df.to_string())

                                                            name  year  selling_price  km_driven      fuel       seller_type transmission                 owner
0                                                  Maruti 800 AC  2007          60000      70000    Petrol        Individual       Manual           First Owner
1                                       Maruti Wagon R LXI Minor  2007         135000      50000    Petrol        Individual       Manual           First Owner
2                                           Hyundai Verna 1.6 SX  2012         600000     100000    Diesel        Individual       Manual           First Owner
3                                         Datsun RediGO T Option  2017         250000      46000    Petrol        Individual       Manual           First Owner
4                                          Honda Amaze VX i-DTEC  2014         450000     141000    Diesel        Individual       Manual          Second Owner
5                                           Maruti Alto LX BSIII  2007         140000     125000    Petrol        Individual       Manual           First Owner
6                                      Hyundai Xcent 1.2 Kappa S  2016         550000      25000    Petrol        Individual       Manual           First Owner
7                                       Tata Indigo Grand Petrol  2014         240000      60000    Petrol        Individual       Manual          Second Owner
8                                       Hyundai Creta 1.6 VTVT S  2015         850000      25000    Petrol        Individual       Manual           First Owner
9                                       Maruti Celerio Green VXI  2017         365000      78000       CNG        Individual       Manual           First Owner
10                                       Chevrolet Sail 1.2 Base  2015         260000      35000    Petrol        Individual       Manual           First Owner
11                                      Tata Indigo Grand Petrol  2014         250000     100000    Petrol        Individual       Manual           First Owner
12                               Toyota Corolla Altis 1.8 VL CVT  2018        1650000      25000    Petrol            Dealer    Automatic           First Owner
13                                                 Maruti 800 AC  2007          60000      70000    Petrol        Individual       Manual           First Owner
14                                      Maruti Wagon R LXI Minor  2007         135000      50000    Petrol        Individual       Manual           First Owner
15                                          Hyundai Verna 1.6 SX  2012         600000     100000    Diesel        Individual       Manual           First Owner
16                                        Datsun RediGO T Option  2017         250000      46000    Petrol        Individual       Manual           First Owner
17                                         Honda Amaze VX i-DTEC  2014         450000     141000    Diesel        Individual       Manual          Second Owner
18                                          Maruti Alto LX BSIII  2007         140000     125000    Petrol        Individual       Manual           First Owner
19                                     Hyundai Xcent 1.2 Kappa S  2016         550000      25000    Petrol        Individual       Manual           First Owner
20                                      Tata Indigo Grand Petrol  2014         240000      60000    Petrol        Individual       Manual          Second Owner
21                                      Hyundai Creta 1.6 VTVT S  2015         850000      25000    Petrol        Individual       Manual           First Owner
22                                      Maruti Celerio Green VXI  2017         365000      78000       CNG        Individual       Manual           First Owner
23                                       Chevrolet Sail 1.2 Base  2015         260000      35000    Petrol        Individual       Manual           First Owner
24                                      Tata Indigo Grand Petrol  2014         250000     100000    Petrol        Individual       Manual           First Owner
25                               Toyota Corolla Altis 1.8 VL CVT  2018        1650000      25000    Petrol            Dealer    Automatic           First Owner
26                                          Maruti Ciaz VXi Plus  2015         585000      24000    Petrol            Dealer       Manual           First Owner
27                                   Hyundai Venue SX Opt Diesel  2019        1195000       5000    Diesel            Dealer       Manual           First Owner
28                             Chevrolet Enjoy TCDi LTZ 7 Seater  2013         390000      33000    Diesel        Individual       Manual          Second Owner
29                                    Jaguar XF 2.2 Litre Luxury  2014        1964999      28000    Diesel            Dealer    Automatic           First Owner
30                          Mercedes-Benz New C-Class 220 CDI AT  2013        1425000      59000    Diesel            Dealer    Automatic           First Owner
31                             Maruti Vitara Brezza ZDi Plus AMT  2018         975000       4500    Diesel            Dealer    Automatic           First Owner
32                                               Audi Q5 2.0 TDI  2011        1190000     175900    Diesel            Dealer    Automatic           First Owner
33                                               Honda City V MT  2018         930000      14500    Petrol            Dealer       Manual           First Owner
34                                    Tata Tigor 1.2 Revotron XT  2018         525000      15000    Petrol        Individual       Manual           First Owner
35                               Audi A6 2.0 TDI  Design Edition  2013        1735000      50000    Diesel            Dealer    Automatic           First Owner
36                Mercedes-Benz New C-Class C 220 CDI Avantgarde  2012        1375000      33800    Diesel            Dealer    Automatic          Second Owner
37                           Skoda Superb Ambition 2.0 TDI CR AT  2011         450000     130400    Diesel            Dealer    Automatic          Second Owner
38                                     Toyota Corolla Altis G AT  2016         900000      50000    Petrol        Individual    Automatic           First Owner
39                         Toyota Innova 2.5 G (Diesel) 7 Seater  2015        1300000      80000    Diesel        Individual       Manual           First Owner
40                              Jeep Compass 1.4 Sport Plus BSIV  2019        1400000      10000    Petrol        Individual       Manual           First Owner
41                      Mercedes-Benz E-Class E 200 CGI Elegance  2010         850000     119000    Petrol            Dealer    Automatic           First Owner
42                                        Hyundai i10 Magna 1.1L  2014         229999      60000    Petrol        Individual       Manual  Fourth & Above Owner
43                                  BMW 3 Series 320d Sport Line  2013        1550000      75800    Diesel            Dealer    Automatic          Second Owner
44                                Audi Q7 35 TDI Quattro Premium  2009        1250000      78000    Diesel            Dealer    Automatic           Third Owner
45                                        Hyundai Elantra CRDi S  2012         625000      40000    Diesel        Individual       Manual           First Owner
46                                     Mahindra Scorpio 1.99 S10  2014        1050000      50000    Diesel        Individual       Manual           First Owner
47                                           Honda City i DTEC V  2014         560000      74000    Diesel        Individual       Manual          Second Owner
48                             Maruti Wagon R VXI BS IV with ABS  2014         290000      64000    Petrol        Individual       Manual          Second Owner
49                                      Maruti Wagon R VXI BS IV  2012         275000      60000    Petrol        Individual       Manual          Second Owner
50                                           Mahindra Scorpio LX  2009         411000     120000    Diesel        Individual       Manual          Second Owner
51                                       Hyundai Santro Xing GLS  2009         150000      79000    Petrol        Individual       Manual           Third Owner
52                              Hyundai Grand i10 1.2 Kappa Asta  2019         500000      15000    Petrol        Individual       Manual           First Owner
53                                               Maruti Alto LXi  2006         100000      80000    Petrol        Individual       Manual           First Owner
54                               Maruti Swift Dzire VDI Optional  2017         725000      18500    Diesel            Dealer       Manual           First Owner
55                                  Maruti Eeco 5 Seater AC BSIV  2018         401000      10200    Petrol            Dealer       Manual           First Owner
56                                   Hyundai i20 Sportz 1.4 CRDi  2018         750000      29000    Diesel            Dealer       Manual           First Owner
57    Maruti Omni Maruti Omni MPI STD BSIII 5-STR W/ IMMOBILISER  2018         310000      28000    Petrol            Dealer       Manual           First Owner
58                                         Maruti Swift ZDi BSIV  2016         665000      46000    Diesel            Dealer       Manual           First Owner
59                  Hyundai i20 2015-2017 Sportz Option 1.4 CRDi  2014         465000      70000    Diesel            Dealer       Manual           First Owner
60                                               Maruti Alto LXi  2012         160000      60000    Petrol        Individual       Manual          Second Owner
61                                      Mahindra Jeep CL 500 MDI  1996         250000      35000    Diesel        Individual       Manual          Second Owner
62                                          Honda City i DTEC VX  2014         675000      90000    Diesel            Dealer       Manual           First Owner
63                                      Maruti Wagon R VXI BS IV  2013         300000      80000    Petrol            Dealer       Manual           First Owner
64                                               Tata Indica DLS  2005          70000      80000    Diesel        Individual       Manual           First Owner
65                                        Hyundai EON Magna Plus  2014         240000      73300    Petrol            Dealer       Manual          Second Owner
66                                               Toyota Etios GD  2014         525000      92000    Diesel            Dealer       Manual           First Owner
67                                               Maruti Alto LXi  2009         151000      66764    Petrol            Dealer       Manual          Second Owner
68                                               Maruti Alto LXi  2009         140000     100000    Petrol        Individual       Manual           First Owner
69                 Chevrolet Tavera Neo LS B3 - 7(C) seats BSIII  2010         280000     350000    Diesel        Individual       Manual          Second Owner
70                              Toyota Corolla Altis Diesel D4DG  2011         350000     230000    Diesel        Individual       Manual           First Owner
71                                 Mahindra Scorpio 1.99 S6 Plus  2017         570000      60000    Diesel        Individual       Manual           First Owner
72                                        Hyundai EON Magna Plus  2018         300000      31000    Petrol        Individual       Manual           First Owner
73                                     Tata Indigo Classic Dicor  2007         100000      39000    Diesel        Individual       Manual           First Owner
74                           Toyota Innova 2.5 V Diesel 8-seater  2009         500000     120000    Diesel        Individual       Manual           Third Owner
75                                Tata Indica Vista Quadrajet LS  2014         125000     166000    Diesel        Individual       Manual  Fourth & Above Owner
76                                          Maruti Swift 1.3 VXi  2006         130000     110000    Petrol        Individual       Manual           Third Owner
77                        Ford EcoSport 1.5 Diesel Titanium BSIV  2017         925000      35000    Diesel        Individual       Manual           First Owner
78                                         Maruti Ciaz 1.3 Delta  2018         750000      60000    Diesel        Individual       Manual           First Owner
79                                          Honda Civic 1.8 V AT  2007         200000      54000    Petrol        Individual    Automatic          Second Owner
80                                        Hyundai i10 Sportz 1.2  2010         248000      63000    Petrol        Individual       Manual          Second Owner
81                                  Skoda Rapid 1.5 TDI Elegance  2014         450000     120000    Diesel        Individual       Manual          Second Owner
82                                              Hyundai Getz GLS  2005          80000     120000    Petrol        Individual       Manual           Third Owner
83                                             Nissan Terrano XL  2014         650000      76000    Petrol        Individual       Manual          Second Owner
84                                 Hyundai Grand i10 CRDi Sportz  2015         450000      80000    Diesel        Individual       Manual           First Owner
85                                  Hyundai Elite i20 Diesel Era  2019         650000      25000    Diesel        Individual       Manual           First Owner
86                                          Honda Amaze S i-VTEC  2016         495000      11958    Petrol            Dealer       Manual           First Owner
87                                               Honda Brio S MT  2015         371000      20000    Petrol            Dealer       Manual           First Owner
88                                   Hyundai Creta 1.6 SX Option  2017        1025000       9000    Petrol            Dealer       Manual           First Owner
89             Mercedes-Benz S-Class S 350d Connoisseurs Edition  2017        8150000       6500    Diesel            Dealer    Automatic           First Owner
90                                        Mahindra XUV500 W8 2WD  2015         750000      70000    Diesel        Individual       Manual           First Owner
91                       Renault Duster 85PS Diesel RxL Optional  2013         600000     120000    Diesel        Individual       Manual           First Owner
92                                        Hyundai Santro Xing XO  2007          80000      58000    Petrol            Dealer       Manual          Second Owner
93                                 Mahindra Bolero 2011-2019 SLE  2013         325000      62200    Diesel            Dealer       Manual           First Owner
94                                  Audi A6 2.0 TDI Premium Plus  2014        1470000      34000    Diesel            Dealer    Automatic          Second Owner
95                               Fiat Avventura MULTIJET Emotion  2015         350000      53000    Diesel        Individual       Manual          Second Owner
96                                               Audi A8 4.2 TDI  2013        2800000      49000    Diesel            Dealer    Automatic           First Owner
97                                           Datsun RediGO 1.0 S  2017         210000      15000    Petrol            Dealer       Manual          Second Owner
98                          Volkswagen Jetta 1.4 TSI Comfortline  2013         450000      50000    Petrol        Individual       Manual           First Owner
99                          Audi A4 2.0 TDI 177 Bhp Premium Plus  2013        1150000      53000    Diesel            Dealer    Automatic           First Owner
100                                         Honda Civic 1.8 V AT  2009         210000      63500    Petrol            Dealer    Automatic           First Owner
101                   Mercedes-Benz E-Class Exclusive E 200 BSIV  2018        4500000       9800    Petrol            Dealer    Automatic           First Owner
102                                      BMW X1 sDrive 20d xLine  2017        2750000      13000    Diesel        Individual    Automatic           First Owner
103                                        Volvo V40 D3 R Design  2018        1975000      21000    Diesel            Dealer    Automatic           First Owner
104                                         Maruti SX4 Zxi BSIII  2008         175000      29173    Petrol            Dealer       Manual           First Owner
105                                           BMW 7 Series 730Ld  2012        2500000      48000    Diesel            Dealer    Automatic           First Owner
106                               Mahindra Bolero Power Plus SLX  2017         628000     120000    Diesel        Individual       Manual           First Owner
107                                      Hyundai Sonata CRDi M/T  2010         600000     100000    Diesel        Individual       Manual           First Owner
108                                Nissan Micra Active XV Petrol  2017         399000      30000    Petrol        Individual       Manual           First Owner
109                                             Mahindra Xylo D4  2018         750000      87000    Diesel        Individual       Manual           First Owner
110                 Hyundai Elite i20 Sportz Plus Dual Tone BSIV  2019         750000      15000    Petrol        Individual       Manual           First Owner
111                                             Renault KWID RXT  2017         315000      16000    Petrol        Individual       Manual           First Owner
112                                      Mahindra Xylo E4 BS III  2012         600000      60000    Diesel        Individual       Manual           First Owner
113                                     Maruti Wagon R LXI Minor  2010         100000      60000    Petrol        Individual       Manual  Fourth & Above Owner
114                                       Maruti SX4 ZXI MT BSIV  2011         250000     110000    Petrol        Individual       Manual           Third Owner
115                                             Renault KWID RXT  2017         350000      25000    Petrol        Individual       Manual           First Owner
116                                     Hyundai Creta 1.4 CRDi S  2016         780000      60000    Diesel        Individual       Manual           First Owner
117                                       Maruti Swift Dzire VDI  2014         434000      79350    Diesel        Individual       Manual          Second Owner
118                           Hyundai Verna 1.6 VTVT AT S Option  2016         690000      80000    Petrol        Individual    Automatic           First Owner
119                                     Mahindra Scorpio LX BSIV  2014         555000      90000    Diesel        Individual       Manual          Second Owner
120                                         Maruti SX4 Vxi BSIII  2007         120000      90000    Petrol        Individual       Manual          Second Owner
121                                            Maruti Ertiga VDI  2014         500000     120000    Diesel        Individual       Manual          Second Owner
122                                        Chevrolet Beat Diesel  2013         165000      60000    Diesel        Individual       Manual          Second Owner
123                                                Maruti Zen LX  2004          95000      50000    Petrol        Individual       Manual           First Owner

## 2.2 вывод первых 5 элементов таблицы

In [30]:
df.head(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

вывод первых 5 элементов через индексацию:

In [31]:
df.iloc[:5]  #iloc- это метод Pandas для выбора данных по их позиции в DataFrame.

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

## 2.3 вывод последних 5 элементов таблицы

In [32]:
df.tail(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

вывод последних 5 элементов через индексацию:

In [33]:
df.iloc[-5:]  #iloc- это метод Pandas для выбора данных по их позиции в DataFrame.

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

## 2.4 использовать функцию describe()

Вычисляет основные статистические характеристики данных в каждом столбце, такие как среднее значение, стандартное отклонение, минимальное и максимальное значения, медиану и квартили.

In [34]:
df.describe().round()

         year  selling_price  km_driven
count  4340.0         4340.0     4340.0
mean   2013.0       504127.0    66216.0
std       4.0       578549.0    46644.0
min    1992.0        20000.0        1.0
25%    2011.0       208750.0    35000.0
50%    2014.0       350000.0    60000.0
75%    2016.0       600000.0    90000.0
max    2020.0      8900000.0   806599.0

## 2.5 считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки) всеми известными вам способами

выбирает значение в первой строке и столбце 'name' по меткам индекса и названию столбца соответственно.

In [35]:
df.loc[0, 'name']

'Maruti 800 AC'

выбирает значение в первой строке и первом столбце по их позициям в DataFrame.

In [36]:
df.iloc[0, 0]

'Maruti 800 AC'

выбирает значение в первой строке и столбце 'name' по меткам индекса и названию столбца соответственно. Этот метод работает быстрее, чем loc, но может использоваться только для выбора одного элемента.

In [37]:
df.at[0, 'name']

'Maruti 800 AC'

выбирает значение в первой строке и первом столбце по их позициям в DataFrame. Этот метод работает быстрее, чем iloc, но может использоваться только для выбора одного элемента.

In [38]:
df.iat[0, 0]

'Maruti 800 AC'

In [39]:
df['name'].values[0]

'Maruti 800 AC'

In [40]:
df._get_value(0, 'name')

'Maruti 800 AC'

## 2.6 фильтрация строк по диапазону индекса

In [41]:
df[0:10]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner

фильтрация строк по меткам индекса:

In [42]:
df.loc[0:10]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
10,Chevrolet Sail 1.2 Base,2015,260000,35000,Petrol,Individual,Manual,First Owner

In [43]:
filter = [0,1,2,3,5,6,7,8,9,10]

df[df.index.isin (filter)] #создает булеву маску, которая содержит значения True для всех индексов строк в DataFrame df, которые находятся в списке filter, и False для всех остальных индексов строк.

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
10,Chevrolet Sail 1.2 Base,2015,260000,35000,Petrol,Individual,Manual,First Owner

## 2.7 фильтрация набора данных по какому-либо условию

In [44]:
df[df['year'] > 2019]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
158,Maruti Wagon R LXI,2020,240000,120000,Petrol,Individual,Manual,First Owner
176,Maruti Alto K10 LXI CNG,2020,282000,40000,CNG,Individual,Manual,First Owner
289,Mahindra XUV500 W11 Option AWD,2020,1400000,25000,Diesel,Dealer,Manual,First Owner
694,Hyundai Grand i10 Nios Magna CRDi,2020,700000,1400,Diesel,Individual,Manual,First Owner
963,Audi A5 Sportback,2020,4700000,1500,Diesel,Individual,Automatic,First Owner
1002,Hyundai Creta 1.4 EX Diesel,2020,1050000,10000,Diesel,Individual,Manual,First Owner
1195,Maruti Baleno Zeta,2020,700000,1100,Petrol,Individual,Manual,First Owner
1291,Maruti Alto 800 VXI,2020,350000,1000,Petrol,Individual,Manual,First Owner
1324,Maruti Swift VXI,2020,619000,1500,Petrol,Individual,Manual,First Owner
1409,Volkswagen Polo 1.0 TSI Highline Plus,2020,802000,5000,Petrol,Individual,Manual,First Owner
1428,Hyundai Grand i10 Nios Sportz,2020,600000,5000,Petrol,Individual,Manual,First Owner
1432,Hyundai Grand i10 Nios AMT Magna,2020,640000,4000,Petrol,Individual,Automatic,First Owner
1516,Mahindra XUV500 W11 Option AWD,2020,1400000,25000,Diesel,Dealer,Manual,First Owner
1575,Renault KWID RXL,2020,300000,20000,Petrol,Individual,Manual,First Owner
1595,Maruti Alto K10 LX,2020,250000,1100,Petrol,Individual,Manual,Fourth & Above Owner
1689,Hyundai Elite i20 Magna Plus BSIV,2020,545000,7300,Petrol,Individual,Manual,First Owner
1714,Ford Freestyle Titanium Diesel,2020,784000,101,Diesel,Dealer,Manual,Test Drive Car
1715,Ford Figo Titanium,2020,635000,101,Petrol,Dealer,Manual,Test Drive Car
1716,Ford Ecosport 1.5 Diesel Titanium,2020,1000000,101,Diesel,Dealer,Manual,Test Drive Car
1774,Ford Aspire Titanium BSIV,2020,828999,1010,Petrol,Dealer,Manual,Test Drive Car
1775,Ford EcoSport 1.5 Ti VCT MT Titanium BE BSIV,2020,1119000,1010,Petrol,Dealer,Manual,Test Drive Car
1776,Ford Figo Titanium,2020,746000,1111,Petrol,Dealer,Manual,Test Drive Car
1777,Ford Ecosport 1.5 Petrol Trend,2020,1030000,1010,Petrol,Dealer,Manual,Test Drive Car
1778,Ford EcoSport 1.5 TDCi Titanium Plus BSIV,2020,1334000,1010,Diesel,Dealer,Manual,Test Drive Car
1779,Ford Freestyle Titanium,2020,811999,1010,Petrol,Dealer,Manual,Test Drive Car
1780,Ford Ecosport Thunder Edition Diesel,2020,1331000,1010,Diesel,Dealer,Manual,Test Drive Car
1781,Ford Freestyle Titanium Plus,2020,852000,1010,Petrol,Dealer,Manual,Test Drive Car
1963,Hyundai Venue SX Opt Diesel,2020,1000000,5000,Diesel,Individual,Manual,First Owner
2016,Tata Altroz XZ,2020,830000,10000,Petrol,Individual,Manual,First Owner
2129,Honda BR-V i-VTEC VX MT,2020,1250000,1100,Petrol,Dealer,Manual,First Owner
2137,Maruti Ertiga 1.5 VDI,2020,550000,90000,Diesel,Individual,Manual,First Owner
2154,Ford Ecosport Sports Petrol,2020,1100000,1000,Petrol,Individual,Manual,First Owner
2211,Hyundai Creta 1.4 EX Diesel,2020,1050000,10000,Diesel,Individual,Manual,First Owner
2360,Renault KWID Climber 1.0 MT Opt BSIV,2020,541000,1000,Petrol,Dealer,Manual,Test Drive Car
2476,Tata Altroz XE,2020,500000,5000,Petrol,Individual,Manual,First Owner
2481,Hyundai Santro Sportz BSIV,2020,520000,5000,Petrol,Individual,Manual,First Owner
2558,Maruti Swift ZXI Plus,2020,550000,5000,Petrol,Individual,Manual,First Owner
2699,Mahindra Scorpio S5 BSIV,2020,1200000,11000,Diesel,Individual,Manual,First Owner
3024,Maruti Alto 800 LXI,2020,347000,5000,Petrol,Individual,Manual,First Owner
3050,Maruti Alto 800 LXI,2020,310000,1700,Petrol,Individual,Manual,First Owner
3112,Maruti Eeco CNG 5 Seater AC BSIV,2020,495000,7000,CNG,Individual,Manual,First Owner
3268,Maruti Swift VXI,2020,619000,1500,Petrol,Individual,Manual,First Owner
3422,Maruti Alto 800 VXI,2020,210000,40000,Petrol,Individual,Manual,First Owner
3431,Hyundai Venue SX Opt Turbo BSIV,2020,1050000,1100,Petrol,Individual,Manual,First Owner
3486,Hyundai Grand i10 1.2 Kappa Magna BSIV,2020,545000,5000,Petrol,Individual,Manual,First Owner
3933,Ford Figo Aspire 1.5 TDCi Titanium,2020,530000,45000,Diesel,Dealer,Manual,First Owner
4105,Tata Harrier XE,2020,426000,1000,Diesel,Individual,Manual,First Owner
4278,Honda Amaze S Petrol BSIV,2020,614000,1000,Petrol,Individual,Manual,First Owner

In [45]:
df[(df['year'] > 2019) & (df['selling_price'] >= 1000000)]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
289,Mahindra XUV500 W11 Option AWD,2020,1400000,25000,Diesel,Dealer,Manual,First Owner
963,Audi A5 Sportback,2020,4700000,1500,Diesel,Individual,Automatic,First Owner
1002,Hyundai Creta 1.4 EX Diesel,2020,1050000,10000,Diesel,Individual,Manual,First Owner
1516,Mahindra XUV500 W11 Option AWD,2020,1400000,25000,Diesel,Dealer,Manual,First Owner
1716,Ford Ecosport 1.5 Diesel Titanium,2020,1000000,101,Diesel,Dealer,Manual,Test Drive Car
1775,Ford EcoSport 1.5 Ti VCT MT Titanium BE BSIV,2020,1119000,1010,Petrol,Dealer,Manual,Test Drive Car
1777,Ford Ecosport 1.5 Petrol Trend,2020,1030000,1010,Petrol,Dealer,Manual,Test Drive Car
1778,Ford EcoSport 1.5 TDCi Titanium Plus BSIV,2020,1334000,1010,Diesel,Dealer,Manual,Test Drive Car
1780,Ford Ecosport Thunder Edition Diesel,2020,1331000,1010,Diesel,Dealer,Manual,Test Drive Car
1963,Hyundai Venue SX Opt Diesel,2020,1000000,5000,Diesel,Individual,Manual,First Owner
2129,Honda BR-V i-VTEC VX MT,2020,1250000,1100,Petrol,Dealer,Manual,First Owner
2154,Ford Ecosport Sports Petrol,2020,1100000,1000,Petrol,Individual,Manual,First Owner
2211,Hyundai Creta 1.4 EX Diesel,2020,1050000,10000,Diesel,Individual,Manual,First Owner
2699,Mahindra Scorpio S5 BSIV,2020,1200000,11000,Diesel,Individual,Manual,First Owner
3431,Hyundai Venue SX Opt Turbo BSIV,2020,1050000,1100,Petrol,Individual,Manual,First Owner

In [46]:
df[df.name.str.startswith('Ford')]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
77,Ford EcoSport 1.5 Diesel Titanium BSIV,2017,925000,35000,Diesel,Individual,Manual,First Owner
134,Ford Figo Aspire 1.2 Ti-VCT Titanium Plus,2015,530000,14272,Petrol,Dealer,Manual,First Owner
135,Ford EcoSport 1.5 Diesel Titanium Plus BSIV,2017,840000,49213,Diesel,Dealer,Manual,First Owner
194,Ford Figo Diesel Titanium,2010,170000,90000,Diesel,Individual,Manual,Third Owner
195,Ford Figo Diesel Titanium,2011,190000,90000,Diesel,Individual,Manual,Third Owner
...,...,...,...,...,...,...,...,...
4205,Ford Figo Aspire 1.5 TDCi Titanium Plus,2015,459999,140730,Diesel,Dealer,Manual,Second Owner
4213,Ford Ecosport 1.5 DV5 MT Titanium,2015,550000,135000,Diesel,Individual,Manual,Second Owner
4276,Ford Fiesta 1.6 ZXi Duratec,2009,233000,58000,Petrol,Individual,Manual,Third Owner
4313,Ford Endeavour 2.2 Titanium AT 4X2,2019,2800000,10000,Diesel,Individual,Automatic,First Owner
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,530000,175000,Diesel,Individual,Manual,Third Owner

In [47]:
df.nlargest(10, 'selling_price')

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner
555,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner
574,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner
593,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner
612,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner
900,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner
919,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner
1023,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner

In [22]:
df[df.fuel.str.contains('Pet')]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

## 2.8 работа с пропущенными значениями (если они есть): удаление строк с пропущенными значениями, заполнение пропущенных значений средним значением по колонке. Если пропущенных значений нет — намеренно их "генерируете", прибивая какие-то куски данных в np.nan

In [48]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [49]:
df.iloc[0:30, 0:30] = np.nan
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014.0,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014.0,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009.0,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016.0,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016.0,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [50]:
df.isnull().sum()

name             30
year             30
selling_price    30
km_driven        30
fuel             30
seller_type      30
transmission     30
owner            30
dtype: int64

In [51]:
df = df.dropna(axis=0)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
30,Mercedes-Benz New C-Class 220 CDI AT,2013.0,1425000.0,59000.0,Diesel,Dealer,Automatic,First Owner
31,Maruti Vitara Brezza ZDi Plus AMT,2018.0,975000.0,4500.0,Diesel,Dealer,Automatic,First Owner
32,Audi Q5 2.0 TDI,2011.0,1190000.0,175900.0,Diesel,Dealer,Automatic,First Owner
33,Honda City V MT,2018.0,930000.0,14500.0,Petrol,Dealer,Manual,First Owner
34,Tata Tigor 1.2 Revotron XT,2018.0,525000.0,15000.0,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014.0,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014.0,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009.0,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016.0,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016.0,225000.0,40000.0,Petrol,Individual,Manual,First Owner

Генрируем пропущенные значения

In [52]:
df.iloc[1:4, 1:4] = np.nan
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
30,Mercedes-Benz New C-Class 220 CDI AT,2013.0,1425000.0,59000.0,Diesel,Dealer,Automatic,First Owner
31,Maruti Vitara Brezza ZDi Plus AMT,NaN,NaN,NaN,Diesel,Dealer,Automatic,First Owner
32,Audi Q5 2.0 TDI,NaN,NaN,NaN,Diesel,Dealer,Automatic,First Owner
33,Honda City V MT,NaN,NaN,NaN,Petrol,Dealer,Manual,First Owner
34,Tata Tigor 1.2 Revotron XT,2018.0,525000.0,15000.0,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014.0,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014.0,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009.0,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016.0,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016.0,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [57]:
numeric_cols = ['year', 'selling_price', 'km_driven']
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
pd.options.display.float_format = '{:.0f}'.format
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,age
30,Mercedes-Benz New C-Class 220 CDI AT,2013,1425000,59000,Diesel,Dealer,Automatic,First Owner,10
31,Maruti Vitara Brezza ZDi Plus AMT,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
32,Audi Q5 2.0 TDI,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
33,Honda City V MT,2013,503618,66248,Petrol,Dealer,Manual,First Owner,10
34,Tata Tigor 1.2 Revotron XT,2018,525000,15000,Petrol,Individual,Manual,First Owner,5
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,14
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,7
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,7

## 2.9. создание нового поля вычисленного на основе значений других полей:

### 2.9.1 через выражение на базе имеющихся колонок,

In [58]:
df['age'] = 2023 - df['year']
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,age
30,Mercedes-Benz New C-Class 220 CDI AT,2013,1425000,59000,Diesel,Dealer,Automatic,First Owner,10
31,Maruti Vitara Brezza ZDi Plus AMT,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
32,Audi Q5 2.0 TDI,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
33,Honda City V MT,2013,503618,66248,Petrol,Dealer,Manual,First Owner,10
34,Tata Tigor 1.2 Revotron XT,2018,525000,15000,Petrol,Individual,Manual,First Owner,5
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,14
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,7
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,7

### 2.9.2 через DataFrame.apply

In [59]:
df['age'] = (2023 - df['year']).apply(lambda x: max(x, 0)) #Функция lambda x: max(x, 0) возвращает значение x, если x
#больше или равно 0, и 0 в противном случае. Это нужно для того, чтобы избежать отрицательных значений возраста.
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,age
30,Mercedes-Benz New C-Class 220 CDI AT,2013,1425000,59000,Diesel,Dealer,Automatic,First Owner,10
31,Maruti Vitara Brezza ZDi Plus AMT,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
32,Audi Q5 2.0 TDI,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
33,Honda City V MT,2013,503618,66248,Petrol,Dealer,Manual,First Owner,10
34,Tata Tigor 1.2 Revotron XT,2018,525000,15000,Petrol,Individual,Manual,First Owner,5
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,14
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,7
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,7

### 2.9.3 через Series.apply

In [60]:
def calculate_age(year):
    return 2023 - year

df['age'] = df['year'].apply(calculate_age)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,age
30,Mercedes-Benz New C-Class 220 CDI AT,2013,1425000,59000,Diesel,Dealer,Automatic,First Owner,10
31,Maruti Vitara Brezza ZDi Plus AMT,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
32,Audi Q5 2.0 TDI,2013,503618,66248,Diesel,Dealer,Automatic,First Owner,10
33,Honda City V MT,2013,503618,66248,Petrol,Dealer,Manual,First Owner,10
34,Tata Tigor 1.2 Revotron XT,2018,525000,15000,Petrol,Individual,Manual,First Owner,5
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,9
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,14
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,7
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,7

## 2.10 сортировка по какому-либо из полей

In [61]:
df = df.sort_values(by='selling_price', ascending=True)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,age
2662,Ford Ikon 1.6 ZXI NXt,2005,20000,25000,Petrol,Individual,Manual,Second Owner,18
2495,Ford Ikon 1.4 ZXi,2000,22000,42743,Petrol,Dealer,Manual,Third Owner,23
2444,Maruti 800 EX,2004,30000,60000,Petrol,Individual,Manual,Third Owner,19
2849,Tata Nano Std BSII,2009,35000,50000,Petrol,Individual,Manual,Third Owner,14
1832,Tata Nano LX SE,2012,35000,35000,Petrol,Individual,Manual,Third Owner,11
...,...,...,...,...,...,...,...,...,...
900,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,4
2258,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,4
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner,7
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner,6
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner,7

In [62]:
df = df.sort_values(by='selling_price', ascending=False)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,age
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner,7
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner,6
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner,7
2258,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,4
900,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,4
...,...,...,...,...,...,...,...,...,...
2849,Tata Nano Std BSII,2009,35000,50000,Petrol,Individual,Manual,Third Owner,14
3206,OpelCorsa 1.4 GL,2002,35000,100000,Petrol,Individual,Manual,Third Owner,21
2444,Maruti 800 EX,2004,30000,60000,Petrol,Individual,Manual,Third Owner,19
2495,Ford Ikon 1.4 ZXi,2000,22000,42743,Petrol,Dealer,Manual,Third Owner,23
2662,Ford Ikon 1.6 ZXI NXt,2005,20000,25000,Petrol,Individual,Manual,Second Owner,18

## 2.11 вычислить несколько статистик по колонкам (используйте встроенные агрегатные функции — любые на выбор)

среднее значение для числовых столбцов

In [63]:
df.mean(numeric_only=True)

year              2013
selling_price   503618
km_driven        66248
age                 10
dtype: float64

стандартное отклонение для числовых столбцов

In [64]:
df.std(numeric_only=True)

year                 4
selling_price   578981
km_driven        46649
age                  4
dtype: float64

Минимальные значения столбцов

In [65]:
df.min(numeric_only=True)

year             1992
selling_price   20000
km_driven           1
age                 3
dtype: float64

Максимальные значения столбцов

In [66]:
df.max(numeric_only=True)

year               2020
selling_price   8900000
km_driven        806599
age                  31
dtype: float64

Считаем медиану каждого столбца

In [67]:
df.median(numeric_only=True)

year              2014
selling_price   350000
km_driven        60000
age                  9
dtype: float64

## 2.12 .value_counts()

In [68]:
df['transmission'].value_counts()

Manual       3865
Automatic     445
Name: transmission, dtype: int64

## 2.13 Вывод уникальных значений колонки через .unique()

In [69]:
df['name'].unique()

array(['Audi RS7 2015-2019 Sportback Performance',
       'Mercedes-Benz S-Class S 350d Connoisseurs Edition',
       'Mercedes-Benz GLS 2016-2020 350d 4MATIC', ..., 'OpelCorsa 1.4 GL',
       'Ford Ikon 1.4 ZXi', 'Ford Ikon 1.6 ZXI NXt'], dtype=object)

In [70]:
df['name'].nunique()

1487

## 2.14 Удалите текущий индекс и создайте новый индекс на базе новой колонки, которая для этого лучше всего подходит

In [71]:
df.reset_index(drop=True, inplace=True)
df.set_index('selling_price', inplace=True)
df

,name,year,km_driven,fuel,seller_type,transmission,owner,age
selling_price,,,,,,,,
8900000,Audi RS7 2015-2019 Sportback Performance,2016,13000,Petrol,Dealer,Automatic,First Owner,7
8150000,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,6500,Diesel,Dealer,Automatic,First Owner,6
5500000,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,77350,Diesel,Dealer,Automatic,First Owner,7
4950000,BMW X5 xDrive 30d xLine,2019,30000,Diesel,Dealer,Automatic,First Owner,4
4950000,BMW X5 xDrive 30d xLine,2019,30000,Diesel,Dealer,Automatic,First Owner,4
...,...,...,...,...,...,...,...,...
35000,Tata Nano Std BSII,2009,50000,Petrol,Individual,Manual,Third Owner,14
35000,OpelCorsa 1.4 GL,2002,100000,Petrol,Individual,Manual,Third Owner,21
30000,Maruti 800 EX,2004,60000,Petrol,Individual,Manual,Third Owner,19
22000,Ford Ikon 1.4 ZXi,2000,42743,Petrol,Dealer,Manual,Third Owner,23
20000,Ford Ikon 1.6 ZXI NXt,2005,25000,Petrol,Individual,Manual,Second Owner,18